[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cubesim"
version = "0.0.1"
description = "Exposure time calculator framework for integral-field spectrographs"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT License"}
authors = [
    {name = "Nelson V. Nunes", email = "nvnunes@yorku.ca"},
]
dependencies = [
    "astropy>=7.0.0",
    "matplotlib>=3.9.0",
    "numpy>=2.2.0",
    "scipy>=1.14.1",
]

[project.urls]
Documentation = "https://github.com/nvnunes/cubesim"
Repository = "https://github.com/nvnunes/cubesim"
Issues = "https://github.com/nvnunes/cubesim/issues"

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
]
docs = [
    "mkdocs>=1.6.0,<2.0",
    "mkdocs-material>=9.5.0",
    "mkdocstrings[python]>=0.26.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["cubesim*"]
